### ISSUE TITLE
Typo in github.io demo: two -> too

### ISSUE THREAD

**Issue by xeyownt** [soegaard/metapict#45]
Hello !

Great project, must definitely use it someday!

Not sure this is worth an issue, but I checked your demo at https://soegaard.github.io/blog/metapict/, and noticed the following typo: `you feel the overlap of the two arrow heads is TWO large` -> `you feel the overlap of the two arrow heads is TOO large`

**Comment by soegaard** [comment]
> Great project, must definitely use it someday!

Thanks.

Thanks for the note. It is now fixed in the source.
